version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      - BACK_NET
  ui:
    build: ./ui
    image: ${USERNAME}/ui:2.0
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - FRONT_NET
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - BACK_NET
  comment:
    build: ./comment
    image: ${USERNAME}comment:1.0
    networks:
      - BACK_NET

volumes:
  post_db:

networks:
  BACK_NET:
    ipam:
      config:
        - subnet: ${BACKNET_SUBNET_PREF}
  FRONT_NET:
    ipam:
      config:
        - subnet: ${FRONTNET_SUBNET_PREF}
